### ISSUE TITLE
Add "eslint" command

### ISSUE THREAD

**Issue by ajripley** [connorphee/league_app#11] opened 2017-10-06 04:00 UTC
ESLint has been added, but there is no command in the package.json to run it. (i.e. "npm run eslint" from the command line)

I propose we add one, and I'd like to make the change.

**Comment by connorphee** [comment] 2017-10-06 05:01
Fixed by #12

**Comment by connorphee** [comment] 2017-10-06 05:07
Not sure if error is caused by this or #10 but I am seeing error:

>  Cannot find module /Users/connorphee/projects/league_app/eslint

if someone wants to tackle it, let me know, if not I will fix it.

**Comment by connorphee** [comment] 2017-10-06 05:11
I believe this issue lies in the script provided in the package.json. I should've looked more carefully before merging but not a huge deal. @ajripley if you would like to fix it, it seems like a pretty easy fix.

**Comment by ajripley** [comment] 2017-10-07 00:23
I am unable to recreate your error. Have you run ```npm install``` after pulling the code?

I have tried both ```npm run eslint --ext=js ./routes ./models ./middleware``` and ```npm run eslint```, and neither are giving me an error.

What command is giving you that error?

**Comment by connorphee** [comment] 2017-10-07 03:03
@ajripley I was able to find my issue, this looks good! Thank you so much! If you are interested in contirbuting more please let me know and I will find more to do!

**Closed by connorphee** 2017-10-07 03:03 UTC
